# Generated by Django 3.1.14 on 2022-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20220526_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='hashtags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
