# Generated by Django 3.1.14 on 2022-05-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20220527_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='name',
            new_name='title',
        ),
    ]
