# Generated by Django 3.1.14 on 2022-05-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20220528_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
