# Generated by Django 3.1.14 on 2022-05-27 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20220528_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='title',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
