# Generated by Django 3.1.14 on 2022-05-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20220528_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='web_address',
            field=models.FilePathField(blank=True, null=True, unique=True),
        ),
    ]
