# Generated by Django 3.1.14 on 2022-05-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20220531_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagegallery',
        ),
    ]
